import { Team, Match, TopScorer, TopAssist, Player } from './types';

// Teams in the league
export const TEAMS: Team[] = [
  {
    id: 't1',
    name: 'Real Bogotano',
    shortName: 'RBO',
    logoColor: 'bg-red-600',
    logoEmoji: '🦁',
    played: 3,
    won: 2,
    drawn: 1,
    lost: 0,
    goalsFor: 7,
    goalsAgainst: 3,
    points: 7,
  },
  {
    id: 't2',
    name: 'Deportivo Palermo',
    shortName: 'DPA',
    logoColor: 'bg-blue-600',
    logoEmoji: '⚡',
    played: 3,
    won: 2,
    drawn: 0,
    lost: 1,
    goalsFor: 6,
    goalsAgainst: 4,
    points: 6,
  },
  {
    id: 't3',
    name: 'Atlético Campestre',
    shortName: 'ACA',
    logoColor: 'bg-emerald-600',
    logoEmoji: '⛰️',
    played: 3,
    won: 1,
    drawn: 2,
    lost: 0,
    goalsFor: 4,
    goalsAgainst: 3,
    points: 5,
  },
  {
    id: 't4',
    name: 'F.C. San Isidro',
    shortName: 'CSI',
    logoColor: 'bg-amber-500',
    logoEmoji: '☀️',
    played: 3,
    won: 1,
    drawn: 1,
    lost: 1,
    goalsFor: 5,
    goalsAgainst: 5,
    points: 4,
  },
  {
    id: 't5',
    name: 'Inter Pradera',
    shortName: 'IPR',
    logoColor: 'bg-teal-600',
    logoEmoji: '🌪️',
    played: 3,
    won: 1,
    drawn: 1,
    lost: 1,
    goalsFor: 3,
    goalsAgainst: 4,
    points: 4,
  },
  {
    id: 't6',
    name: 'Unión Estudiantil',
    shortName: 'UES',
    logoColor: 'bg-indigo-600',
    logoEmoji: '🎓',
    played: 3,
    won: 1,
    drawn: 0,
    lost: 2,
    goalsFor: 4,
    goalsAgainst: 6,
    points: 3,
  },
  {
    id: 't7',
    name: 'La Academia F.C.',
    shortName: 'LAC',
    logoColor: 'bg-orange-600',
    logoEmoji: '🛡️',
    played: 3,
    won: 0,
    drawn: 2,
    lost: 1,
    goalsFor: 3,
    goalsAgainst: 5,
    points: 2,
  },
  {
    id: 't8',
    name: 'Estrella del Sur',
    shortName: 'EDS',
    logoColor: 'bg-violet-600',
    logoEmoji: '⭐',
    played: 3,
    won: 0,
    drawn: 1,
    lost: 2,
    goalsFor: 2,
    goalsAgainst: 4,
    points: 1,
  },
];

// Players by team to construct lineups
export const TEAM_PLAYERS: Record<string, Player[]> = {
  t1: [
    { id: 'p1_1', name: 'Mateo González', number: 1, position: 'POR' },
    { id: 'p1_2', name: 'Andrés Castro', number: 4, position: 'DEF' },
    { id: 'p1_3', name: 'Carlos Mendoza', number: 2, position: 'DEF' },
    { id: 'p1_4', name: 'Sebastián Ortiz', number: 14, position: 'DEF' },
    { id: 'p1_5', name: 'Juan David Pérez', number: 6, position: 'MED' },
    { id: 'p1_6', name: 'Santiago Gómez', number: 8, position: 'MED' },
    { id: 'p1_7', name: 'Felipe Cardona', number: 10, position: 'MED' },
    { id: 'p1_8', name: 'Daniel Restrepo', number: 9, position: 'DEL', goals: 4, assists: 0 },
    { id: 'p1_9', name: 'Julián Quiñones', number: 11, position: 'DEL', goals: 2, assists: 2 },
    { id: 'p1_10', name: 'Esteban Arias', number: 13, position: 'DEF' },
    { id: 'p1_11', name: 'Nicolás Bernal', number: 7, position: 'MED', goals: 1, assists: 1 },
    // Subs
    { id: 'p1_12', name: 'Diego Medina', number: 12, position: 'POR' },
    { id: 'p1_13', name: 'Mauricio Villa', number: 18, position: 'MED' },
    { id: 'p1_14', name: 'Camilo Rojas', number: 22, position: 'DEL' },
    { id: 'p1_15', name: 'Jorge Tovar', number: 5, position: 'DEF' },
  ],
  t2: [
    { id: 'p2_1', name: 'Lucas Rossi', number: 12, position: 'POR' },
    { id: 'p2_2', name: 'Mauro Díaz', number: 3, position: 'DEF' },
    { id: 'p2_3', name: 'Fabricio Romano', number: 2, position: 'DEF' },
    { id: 'p2_4', name: 'Bautista Solari', number: 6, position: 'DEF' },
    { id: 'p2_5', name: 'Gino Costa', number: 5, position: 'MED' },
    { id: 'p2_6', name: 'Filippo Inzaghi', number: 9, position: 'DEL', goals: 3, assists: 1 },
    { id: 'p2_7', name: 'Matías Palacios', number: 10, position: 'MED', goals: 1, assists: 3 },
    { id: 'p2_8', name: 'Lorenzo Silva', number: 8, position: 'MED', goals: 1 },
    { id: 'p2_9', name: 'Valentino López', number: 7, position: 'DEL', goals: 1, assists: 1 },
    { id: 'p2_10', name: 'Enzo Fernández', number: 4, position: 'MED' },
    { id: 'p2_11', name: 'Alejo Romero', number: 15, position: 'DEF' },
    // Subs
    { id: 'p2_12', name: 'Thiago Almada', number: 1, position: 'POR' },
    { id: 'p2_13', name: 'Claudio Echeverri', number: 11, position: 'MED' },
    { id: 'p2_14', name: 'Franco Armani', number: 13, position: 'DEF' },
    { id: 'p2_15', name: 'Gianluca Prestianni', number: 19, position: 'DEL' },
  ],
  t3: [
    { id: 'p3_1', name: 'Eduardo Vargas', number: 1, position: 'POR' },
    { id: 'p3_2', name: 'Marcos Rojo', number: 4, position: 'DEF' },
    { id: 'p3_3', name: 'Gary Medel', number: 17, position: 'DEF' },
    { id: 'p3_4', name: 'Jean Beausejour', number: 15, position: 'DEF' },
    { id: 'p3_5', name: 'Arturo Vidal', number: 8, position: 'MED', goals: 1, assists: 1 },
    { id: 'p3_6', name: 'Charles Aránguiz', number: 20, position: 'MED', goals: 1, assists: 0 },
    { id: 'p3_7', name: 'Marcelo Díaz', number: 21, position: 'MED' },
    { id: 'p3_8', name: 'Alexis Sánchez', number: 7, position: 'DEL', goals: 1, assists: 2 },
    { id: 'p3_9', name: 'Mauricio Pinilla', number: 9, position: 'DEL', goals: 1 },
    { id: 'p3_10', name: 'José Fuenzalida', number: 6, position: 'MED' },
    { id: 'p3_11', name: 'Gonzalo Jara', number: 18, position: 'DEF' },
    // Subs
    { id: 'p3_12', name: 'Johnny Herrera', number: 12, position: 'POR' },
    { id: 'p3_13', name: 'Felipe Gutiérrez', number: 10, position: 'MED' },
    { id: 'p3_14', name: 'Eduardo Vargas', number: 11, position: 'DEL' },
  ],
  t4: [
    { id: 'p4_1', name: 'Guillermo Ochoa', number: 1, position: 'POR' },
    { id: 'p4_2', name: 'Rafael Márquez', number: 4, position: 'DEF' },
    { id: 'p4_3', name: 'Hector Moreno', number: 15, position: 'DEF' },
    { id: 'p4_4', name: 'Miguel Layún', number: 19, position: 'DEF' },
    { id: 'p4_5', name: 'Andrés Guardado', number: 18, position: 'MED', goals: 1, assists: 1 },
    { id: 'p4_6', name: 'Héctor Herrera', number: 16, position: 'MED' },
    { id: 'p4_7', name: 'Carlos Peña', number: 8, position: 'MED', goals: 1 },
    { id: 'p4_8', name: 'Giovani dos Santos', number: 10, position: 'DEL', goals: 1, assists: 1 },
    { id: 'p4_9', name: 'Oribe Peralta', number: 19, position: 'DEL', goals: 2, assists: 0 },
    { id: 'p4_10', name: 'Paul Aguilar', number: 22, position: 'DEF' },
    { id: 'p4_11', name: 'Marco Fabián', number: 11, position: 'MED' },
    // Subs
    { id: 'p4_12', name: 'José Corona', number: 12, position: 'POR' },
    { id: 'p4_13', name: 'Javier Hernández', number: 14, position: 'DEL' },
    { id: 'p4_14', name: 'Alan Pulido', number: 17, position: 'DEL' },
  ],
  t5: [
    { id: 'p5_1', name: 'Samir Handanovic', number: 1, position: 'POR' },
    { id: 'p5_2', name: 'Milan Skriniar', number: 37, position: 'DEF' },
    { id: 'p5_3', name: 'Stefan de Vrij', number: 6, position: 'DEF' },
    { id: 'p5_4', name: 'Alessandro Bastoni', number: 95, position: 'DEF' },
    { id: 'p5_5', name: 'Marcelo Brozovic', number: 77, position: 'MED' },
    { id: 'p5_6', name: 'Nicolò Barella', number: 23, position: 'MED', goals: 1, assists: 1 },
    { id: 'p5_7', name: 'Hakan Çalhanoglu', number: 20, position: 'MED', goals: 1, assists: 1 },
    { id: 'p5_8', name: 'Ivan Perisic', number: 14, position: 'MED' },
    { id: 'p5_9', name: 'Lautaro Martínez', number: 10, position: 'DEL', goals: 1 },
    { id: 'p5_10', name: 'Edin Dzeko', number: 9, position: 'DEL' },
    { id: 'p5_11', name: 'Denzel Dumfries', number: 2, position: 'DEF' },
    // Subs
    { id: 'p5_12', name: 'Alex Cordaz', number: 21, position: 'POR' },
    { id: 'p5_13', name: 'Alexis Sánchez', number: 7, position: 'DEL' },
    { id: 'p5_14', name: 'Roberto Gagliardini', number: 5, position: 'MED' },
  ],
  t6: [
    { id: 'p6_1', name: 'Manuel Neuer', number: 1, position: 'POR' },
    { id: 'p6_2', name: 'Jerome Boateng', number: 17, position: 'DEF' },
    { id: 'p6_3', name: 'Mats Hummels', number: 5, position: 'DEF' },
    { id: 'p6_4', name: 'Philipp Lahm', number: 21, position: 'DEF' },
    { id: 'p6_5', name: 'Bastian Schweinsteiger', number: 7, position: 'MED', goals: 1 },
    { id: 'p6_6', name: 'Sami Khedira', number: 6, position: 'MED' },
    { id: 'p6_7', name: 'Toni Kroos', number: 18, position: 'MED', goals: 1, assists: 2 },
    { id: 'p6_8', name: 'Mesut Özil', number: 8, position: 'MED', goals: 1, assists: 1 },
    { id: 'p6_9', name: 'Thomas Müller', number: 13, position: 'DEL', goals: 1 },
    { id: 'p6_10', name: 'Miroslav Klose', number: 11, position: 'DEL' },
    { id: 'p6_11', name: 'Benedikt Höwedes', number: 4, position: 'DEF' },
    // Subs
    { id: 'p6_12', name: 'Ron-Robert Zieler', number: 12, position: 'POR' },
    { id: 'p6_13', name: 'Mario Götze', number: 19, position: 'MED' },
    { id: 'p6_14', name: 'Lukas Podolski', number: 10, position: 'DEL' },
  ],
  t7: [
    { id: 'p7_1', name: 'Iker Casillas', number: 1, position: 'POR' },
    { id: 'p7_2', name: 'Sergio Ramos', number: 15, position: 'DEF' },
    { id: 'p7_3', name: 'Carles Puyol', number: 5, position: 'DEF' },
    { id: 'p7_4', name: 'Gerard Piqué', number: 3, position: 'DEF' },
    { id: 'p7_5', name: 'Joan Capdevila', number: 11, position: 'DEF' },
    { id: 'p7_6', name: 'Sergio Busquets', number: 16, position: 'MED' },
    { id: 'p7_7', name: 'Xabi Alonso', number: 14, position: 'MED' },
    { id: 'p7_8', name: 'Xavi Hernández', number: 8, position: 'MED', assists: 2 },
    { id: 'p7_9', name: 'Andrés Iniesta', number: 6, position: 'MED', goals: 1 },
    { id: 'p7_10', name: 'David Villa', number: 7, position: 'DEL', goals: 2 },
    { id: 'p7_11', name: 'Pedro Rodríguez', number: 18, position: 'DEL' },
    // Subs
    { id: 'p7_12', name: 'Victor Valdés', number: 12, position: 'POR' },
    { id: 'p7_13', name: 'Cesc Fábregas', number: 10, position: 'MED' },
    { id: 'p7_14', name: 'Fernando Torres', number: 9, position: 'DEL' },
  ],
  t8: [
    { id: 'p8_1', name: 'Hugo Lloris', number: 1, position: 'POR' },
    { id: 'p8_2', name: 'Raphaël Varane', number: 4, position: 'DEF' },
    { id: 'p8_3', name: 'Samuel Umtiti', number: 5, position: 'DEF' },
    { id: 'p8_4', name: 'Lucas Hernandez', number: 21, position: 'DEF' },
    { id: 'p8_5', name: 'Benjamin Pavard', number: 2, position: 'DEF', goals: 1 },
    { id: 'p8_6', name: 'N\'Golo Kanté', number: 13, position: 'MED' },
    { id: 'p8_7', name: 'Paul Pogba', number: 6, position: 'MED', goals: 1 },
    { id: 'p8_8', name: 'Blaise Matuidi', number: 14, position: 'MED' },
    { id: 'p8_9', name: 'Antoine Griezmann', number: 7, position: 'DEL', assists: 2 },
    { id: 'p8_10', name: 'Kylian Mbappé', number: 10, position: 'DEL', goals: 0 },
    { id: 'p8_11', name: 'Olivier Giroud', number: 9, position: 'DEL' },
    // Subs
    { id: 'p8_12', name: 'Steve Mandanda', number: 16, position: 'POR' },
    { id: 'p8_13', name: 'Corentin Tolisso', number: 12, position: 'MED' },
    { id: 'p8_14', name: 'Ousmane Dembélé', number: 11, position: 'DEL' },
  ],
};

// Simulated matches
export const MATCHES: Match[] = [
  // --- JORNADA 1 ---
  {
    id: 'm1_1',
    homeTeamId: 't1', // Real Bogotano
    awayTeamId: 't2', // Deportivo Palermo
    homeScore: 3,
    awayScore: 1,
    status: 'played',
    date: '2026-06-20',
    time: '14:00',
    pitch: 'Cancha Principal - Club Campestre',
    referee: 'José Manuel Santos',
    round: 1,
    stats: {
      possession: [54, 46],
      shots: [14, 9],
      shotsOnTarget: [7, 4],
      fouls: [12, 15],
      corners: [6, 4],
      yellowCards: [2, 3],
      redCards: [0, 0],
    },
    lineups: {
      home: {
        starting: TEAM_PLAYERS.t1.slice(0, 11),
        subs: TEAM_PLAYERS.t1.slice(11),
        formation: '4-3-3',
      },
      away: {
        starting: TEAM_PLAYERS.t2.slice(0, 11),
        subs: TEAM_PLAYERS.t2.slice(11),
        formation: '4-4-2',
      },
    },
    events: [
      {
        id: 'e1',
        minute: 12,
        type: 'goal',
        team: 'home',
        player: 'Daniel Restrepo',
        detail: 'Asistencia de Julián Quiñones. Remate cruzado de pierna derecha.',
      },
      {
        id: 'e2',
        minute: 28,
        type: 'yellow_card',
        team: 'away',
        player: 'Fabricio Romano',
        detail: 'Falta táctica para cortar contraataque rápido.',
      },
      {
        id: 'e3',
        minute: 34,
        type: 'goal',
        team: 'away',
        player: 'Filippo Inzaghi',
        detail: 'Asistencia de Matías Palacios. Cabezazo letal tras tiro libre de costado.',
      },
      {
        id: 'e4',
        minute: 44,
        type: 'yellow_card',
        team: 'home',
        player: 'Carlos Mendoza',
        detail: 'Falta fuerte sobre Valentino López en el medio campo.',
      },
      {
        id: 'e5',
        minute: 55,
        type: 'goal',
        team: 'home',
        player: 'Daniel Restrepo',
        detail: 'Asistencia de Nicolás Bernal. Define mano a mano tras pase filtrado.',
      },
      {
        id: 'e6',
        minute: 68,
        type: 'substitution',
        team: 'away',
        player: 'Claudio Echeverri',
        detail: 'Entra por Lorenzo Silva',
      },
      {
        id: 'e7',
        minute: 75,
        type: 'yellow_card',
        team: 'away',
        player: 'Bautista Solari',
        detail: 'Protestas reiteradas al árbitro.',
      },
      {
        id: 'e8',
        minute: 82,
        type: 'goal',
        team: 'home',
        player: 'Nicolás Bernal',
        detail: 'Golazo de tiro libre directo que entra rozando el travesaño.',
      },
      {
        id: 'e9',
        minute: 88,
        type: 'substitution',
        team: 'home',
        player: 'Mauricio Villa',
        detail: 'Entra por Santiago Gómez',
      },
    ],
  },
  {
    id: 'm1_2',
    homeTeamId: 't3', // Atlético Campestre
    awayTeamId: 't4', // F.C. San Isidro
    homeScore: 1,
    awayScore: 1,
    status: 'played',
    date: '2026-06-20',
    time: '16:00',
    pitch: 'Cancha Principal - Club Campestre',
    referee: 'María Camila Restrepo',
    round: 1,
    stats: {
      possession: [51, 49],
      shots: [10, 11],
      shotsOnTarget: [4, 5],
      fouls: [10, 11],
      corners: [5, 3],
      yellowCards: [1, 2],
      redCards: [0, 0],
    },
    lineups: {
      home: {
        starting: TEAM_PLAYERS.t3.slice(0, 11),
        subs: TEAM_PLAYERS.t3.slice(11),
        formation: '4-3-3',
      },
      away: {
        starting: TEAM_PLAYERS.t4.slice(0, 11),
        subs: TEAM_PLAYERS.t4.slice(11),
        formation: '4-4-2',
      },
    },
    events: [
      {
        id: 'e10',
        minute: 23,
        type: 'goal',
        team: 'away',
        player: 'Oribe Peralta',
        detail: 'Asistencia de Giovani dos Santos. Remate de primera tras centro bajo.',
      },
      {
        id: 'e11',
        minute: 41,
        type: 'yellow_card',
        team: 'away',
        player: 'Rafael Márquez',
        detail: 'Infracción táctica sobre Alexis Sánchez.',
      },
      {
        id: 'e12',
        minute: 67,
        type: 'goal',
        team: 'home',
        player: 'Arturo Vidal',
        detail: 'Asistencia de Alexis Sánchez. Penal perfectamente cobrado al palo izquierdo.',
      },
    ],
  },
  {
    id: 'm1_3',
    homeTeamId: 't5', // Inter Pradera
    awayTeamId: 't6', // Unión Estudiantil
    homeScore: 2,
    awayScore: 1,
    status: 'played',
    date: '2026-06-21',
    time: '10:00',
    pitch: 'Cancha Alterna - Sede Pradera',
    referee: 'Fernando Ruiz',
    round: 1,
    stats: {
      possession: [48, 52],
      shots: [8, 12],
      shotsOnTarget: [4, 6],
      fouls: [14, 9],
      corners: [3, 7],
      yellowCards: [3, 1],
      redCards: [1, 0], // Red card for t5!
    },
    lineups: {
      home: {
        starting: TEAM_PLAYERS.t5.slice(0, 11),
        subs: TEAM_PLAYERS.t5.slice(11),
        formation: '3-5-2',
      },
      away: {
        starting: TEAM_PLAYERS.t6.slice(0, 11),
        subs: TEAM_PLAYERS.t6.slice(11),
        formation: '4-3-3',
      },
    },
    events: [
      {
        id: 'e13',
        minute: 15,
        type: 'goal',
        team: 'home',
        player: 'Nicolò Barella',
        detail: 'Asistencia de Hakan Çalhanoglu. Disparo de media distancia que sorprende a Neuer.',
      },
      {
        id: 'e14',
        minute: 38,
        type: 'yellow_card',
        team: 'home',
        player: 'Milan Skriniar',
        detail: 'Corte deslizante tardío.',
      },
      {
        id: 'e15',
        minute: 54,
        type: 'goal',
        team: 'home',
        player: 'Hakan Çalhanoglu',
        detail: 'Asistencia de Nicolò Barella. Golazo de tiro libre raso por debajo de la barrera.',
      },
      {
        id: 'e16',
        minute: 72,
        type: 'red_card',
        team: 'home',
        player: 'Milan Skriniar',
        detail: 'Doble tarjeta amarilla tras cortar una opción manifiesta de gol.',
      },
      {
        id: 'e17',
        minute: 74,
        type: 'goal',
        team: 'away',
        player: 'Toni Kroos',
        detail: 'Cobro de tiro libre que supera la barrera y se cuelga del ángulo derecho.',
      },
    ],
  },
  {
    id: 'm1_4',
    homeTeamId: 't7', // La Academia F.C.
    awayTeamId: 't8', // Estrella del Sur
    homeScore: 1,
    awayScore: 1,
    status: 'played',
    date: '2026-06-21',
    time: '12:00',
    pitch: 'Cancha Alterna - Sede Pradera',
    referee: 'Andrés Barreto',
    round: 1,
    stats: {
      possession: [58, 42],
      shots: [11, 7],
      shotsOnTarget: [5, 3],
      fouls: [8, 12],
      corners: [6, 2],
      yellowCards: [1, 2],
      redCards: [0, 0],
    },
    lineups: {
      home: {
        starting: TEAM_PLAYERS.t7.slice(0, 11),
        subs: TEAM_PLAYERS.t7.slice(11),
        formation: '4-3-3',
      },
      away: {
        starting: TEAM_PLAYERS.t8.slice(0, 11),
        subs: TEAM_PLAYERS.t8.slice(11),
        formation: '4-4-2',
      },
    },
    events: [
      {
        id: 'e18',
        minute: 30,
        type: 'goal',
        team: 'away',
        player: 'Benjamin Pavard',
        detail: 'Asistencia de Antoine Griezmann. Volea espectacular desde fuera del área.',
      },
      {
        id: 'e19',
        minute: 62,
        type: 'goal',
        team: 'home',
        player: 'David Villa',
        detail: 'Asistencia de Xavi Hernández. Definición cruzada impecable.',
      },
    ],
  },

  // --- JORNADA 2 ---
  {
    id: 'm2_1',
    homeTeamId: 't2', // Deportivo Palermo
    awayTeamId: 't5', // Inter Pradera
    homeScore: 2,
    awayScore: 0,
    status: 'played',
    date: '2026-06-27',
    time: '14:00',
    pitch: 'Cancha Principal - Club Campestre',
    referee: 'Juan Sebastián Vargas',
    round: 2,
    stats: {
      possession: [52, 48],
      shots: [12, 8],
      shotsOnTarget: [6, 2],
      fouls: [11, 14],
      corners: [4, 3],
      yellowCards: [2, 4],
      redCards: [0, 0],
    },
    lineups: {
      home: {
        starting: TEAM_PLAYERS.t2.slice(0, 11),
        subs: TEAM_PLAYERS.t2.slice(11),
        formation: '4-4-2',
      },
      away: {
        starting: TEAM_PLAYERS.t5.slice(0, 11),
        subs: TEAM_PLAYERS.t5.slice(11),
        formation: '3-5-2',
      },
    },
    events: [
      {
        id: 'e20',
        minute: 19,
        type: 'goal',
        team: 'home',
        player: 'Filippo Inzaghi',
        detail: 'Asistencia de Matías Palacios. Anticipación letal en el primer palo.',
      },
      {
        id: 'e21',
        minute: 73,
        type: 'goal',
        team: 'home',
        player: 'Matías Palacios',
        detail: 'Golazo de tiro libre por encima de la barrera.',
      },
    ],
  },
  {
    id: 'm2_2',
    homeTeamId: 't4', // F.C. San Isidro
    awayTeamId: 't1', // Real Bogotano
    homeScore: 1,
    awayScore: 3,
    status: 'played',
    date: '2026-06-27',
    time: '16:00',
    pitch: 'Cancha Principal - Club Campestre',
    referee: 'Carlos Alberto Ortega',
    round: 2,
    stats: {
      possession: [43, 57],
      shots: [9, 15],
      shotsOnTarget: [4, 9],
      fouls: [13, 10],
      corners: [3, 8],
      yellowCards: [2, 1],
      redCards: [0, 0],
    },
    lineups: {
      home: {
        starting: TEAM_PLAYERS.t4.slice(0, 11),
        subs: TEAM_PLAYERS.t4.slice(11),
        formation: '4-4-2',
      },
      away: {
        starting: TEAM_PLAYERS.t1.slice(0, 11),
        subs: TEAM_PLAYERS.t1.slice(11),
        formation: '4-3-3',
      },
    },
    events: [
      {
        id: 'e22',
        minute: 8,
        type: 'goal',
        team: 'away',
        player: 'Daniel Restrepo',
        detail: 'Asistencia de Julián Quiñones. Remate raso de zurda tras gran habilitación.',
      },
      {
        id: 'e23',
        minute: 29,
        type: 'goal',
        team: 'home',
        player: 'Andrés Guardado',
        detail: 'Pena máxima ejecutada con gran potencia al centro.',
      },
      {
        id: 'e24',
        minute: 54,
        type: 'goal',
        team: 'away',
        player: 'Julián Quiñones',
        detail: 'Remate colocado de pierna derecha tras gran desborde individual.',
      },
      {
        id: 'e25',
        minute: 81,
        type: 'goal',
        team: 'away',
        player: 'Daniel Restrepo',
        detail: 'Aprovecha rebote del guardameta dentro del área chica.',
      },
    ],
  },
  {
    id: 'm2_3',
    homeTeamId: 't6', // Unión Estudiantil
    awayTeamId: 't7', // La Academia F.C.
    homeScore: 2,
    awayScore: 1,
    status: 'played',
    date: '2026-06-28',
    time: '10:00',
    pitch: 'Cancha Alterna - Sede Pradera',
    referee: 'Diana Carolina Soto',
    round: 2,
    stats: {
      possession: [45, 55],
      shots: [11, 10],
      shotsOnTarget: [5, 4],
      fouls: [12, 9],
      corners: [4, 6],
      yellowCards: [2, 1],
      redCards: [0, 0],
    },
    lineups: {
      home: {
        starting: TEAM_PLAYERS.t6.slice(0, 11),
        subs: TEAM_PLAYERS.t6.slice(11),
        formation: '4-3-3',
      },
      away: {
        starting: TEAM_PLAYERS.t7.slice(0, 11),
        subs: TEAM_PLAYERS.t7.slice(11),
        formation: '4-3-3',
      },
    },
    events: [
      {
        id: 'e26',
        minute: 14,
        type: 'goal',
        team: 'away',
        player: 'Andrés Iniesta',
        detail: 'Remate potente tras pase en diagonal de David Villa.',
      },
      {
        id: 'e27',
        minute: 49,
        type: 'goal',
        team: 'home',
        player: 'Bastian Schweinsteiger',
        detail: 'Asistencia de Toni Kroos. Cabezazo contundente en tiro de esquina.',
      },
      {
        id: 'e28',
        minute: 85,
        type: 'goal',
        team: 'home',
        player: 'Mesut Özil',
        detail: 'Asistencia de Toni Kroos. Remate con rosca al poste lejano.',
      },
    ],
  },
  {
    id: 'm2_4',
    homeTeamId: 't8', // Estrella del Sur
    awayTeamId: 't3', // Atlético Campestre
    homeScore: 0,
    awayScore: 1,
    status: 'played',
    date: '2026-06-28',
    time: '12:00',
    pitch: 'Cancha Alterna - Sede Pradera',
    referee: 'Eduardo Lara',
    round: 2,
    stats: {
      possession: [46, 54],
      shots: [8, 11],
      shotsOnTarget: [3, 6],
      fouls: [15, 11],
      corners: [2, 5],
      yellowCards: [3, 2],
      redCards: [0, 0],
    },
    lineups: {
      home: {
        starting: TEAM_PLAYERS.t8.slice(0, 11),
        subs: TEAM_PLAYERS.t8.slice(11),
        formation: '4-4-2',
      },
      away: {
        starting: TEAM_PLAYERS.t3.slice(0, 11),
        subs: TEAM_PLAYERS.t3.slice(11),
        formation: '4-3-3',
      },
    },
    events: [
      {
        id: 'e29',
        minute: 60,
        type: 'goal',
        team: 'away',
        player: 'Charles Aránguiz',
        detail: 'Asistencia de Arturo Vidal. Remate colocado desde la media luna del área.',
      },
    ],
  },

  // --- JORNADA 3 ---
  {
    id: 'm3_1',
    homeTeamId: 't1', // Real Bogotano
    awayTeamId: 't3', // Atlético Campestre
    homeScore: 1,
    awayScore: 1,
    status: 'played',
    date: '2026-07-04',
    time: '14:00',
    pitch: 'Cancha Principal - Club Campestre',
    referee: 'José Manuel Santos',
    round: 3,
    stats: {
      possession: [56, 44],
      shots: [13, 9],
      shotsOnTarget: [6, 4],
      fouls: [11, 13],
      corners: [7, 3],
      yellowCards: [2, 2],
      redCards: [0, 0],
    },
    lineups: {
      home: {
        starting: TEAM_PLAYERS.t1.slice(0, 11),
        subs: TEAM_PLAYERS.t1.slice(11),
        formation: '4-3-3',
      },
      away: {
        starting: TEAM_PLAYERS.t3.slice(0, 11),
        subs: TEAM_PLAYERS.t3.slice(11),
        formation: '4-3-3',
      },
    },
    events: [
      {
        id: 'e30',
        minute: 40,
        type: 'goal',
        team: 'home',
        player: 'Julián Quiñones',
        detail: 'Remate potente tras desborde de Daniel Restrepo.',
      },
      {
        id: 'e31',
        minute: 71,
        type: 'goal',
        team: 'away',
        player: 'Mauricio Pinilla',
        detail: 'Asistencia de Alexis Sánchez. Chilena espectacular que clava en el ángulo.',
      },
    ],
  },
  {
    id: 'm3_2',
    homeTeamId: 't2', // Deportivo Palermo
    awayTeamId: 't6', // Unión Estudiantil
    homeScore: 3,
    awayScore: 1,
    status: 'played',
    date: '2026-07-04',
    time: '16:00',
    pitch: 'Cancha Principal - Club Campestre',
    referee: 'Fernando Ruiz',
    round: 3,
    stats: {
      possession: [53, 47],
      shots: [15, 10],
      shotsOnTarget: [8, 4],
      fouls: [9, 12],
      corners: [6, 4],
      yellowCards: [1, 2],
      redCards: [0, 0],
    },
    lineups: {
      home: {
        starting: TEAM_PLAYERS.t2.slice(0, 11),
        subs: TEAM_PLAYERS.t2.slice(11),
        formation: '4-4-2',
      },
      away: {
        starting: TEAM_PLAYERS.t6.slice(0, 11),
        subs: TEAM_PLAYERS.t6.slice(11),
        formation: '4-3-3',
      },
    },
    events: [
      {
        id: 'e32',
        minute: 11,
        type: 'goal',
        team: 'home',
        player: 'Filippo Inzaghi',
        detail: 'Asistencia de Matías Palacios. Aprovecha mala salida del portero rival.',
      },
      {
        id: 'e33',
        minute: 27,
        type: 'goal',
        team: 'home',
        player: 'Valentino López',
        detail: 'Asistencia de Filippo Inzaghi. Cabezazo bombeado.',
      },
      {
        id: 'e34',
        minute: 59,
        type: 'goal',
        team: 'away',
        player: 'Thomas Müller',
        detail: 'Asistencia de Mesut Özil. Rebote de derecha en el poste que luego ingresa.',
      },
      {
        id: 'e35',
        minute: 82,
        type: 'goal',
        team: 'home',
        player: 'Lorenzo Silva',
        detail: 'Asistencia de Valentino López. Disparo raso cruzado espectacular.',
      },
    ],
  },
  {
    id: 'm3_3',
    homeTeamId: 't5', // Inter Pradera
    awayTeamId: 't8', // Estrella del Sur
    homeScore: 1,
    awayScore: 1,
    status: 'played',
    date: '2026-07-05',
    time: '10:00',
    pitch: 'Cancha Alterna - Sede Pradera',
    referee: 'Andrés Barreto',
    round: 3,
    stats: {
      possession: [50, 50],
      shots: [10, 9],
      shotsOnTarget: [4, 4],
      fouls: [11, 14],
      corners: [5, 4],
      yellowCards: [2, 3],
      redCards: [0, 0],
    },
    lineups: {
      home: {
        starting: TEAM_PLAYERS.t5.slice(0, 11),
        subs: TEAM_PLAYERS.t5.slice(11),
        formation: '3-5-2',
      },
      away: {
        starting: TEAM_PLAYERS.t8.slice(0, 11),
        subs: TEAM_PLAYERS.t8.slice(11),
        formation: '4-4-2',
      },
    },
    events: [
      {
        id: 'e36',
        minute: 34,
        type: 'goal',
        team: 'away',
        player: 'Paul Pogba',
        detail: 'Asistencia de Antoine Griezmann. Bombazo de 30 metros al ángulo.',
      },
      {
        id: 'e37',
        minute: 66,
        type: 'goal',
        team: 'home',
        player: 'Lautaro Martínez',
        detail: 'Controla con el pecho en el área y define de volea.',
      },
    ],
  },
  {
    id: 'm3_4',
    homeTeamId: 't7', // La Academia F.C.
    awayTeamId: 't4', // F.C. San Isidro
    homeScore: 1,
    awayScore: 3,
    status: 'played',
    date: '2026-07-05',
    time: '12:00',
    pitch: 'Cancha Alterna - Sede Pradera',
    referee: 'María Camila Restrepo',
    round: 3,
    stats: {
      possession: [52, 48],
      shots: [12, 14],
      shotsOnTarget: [5, 8],
      fouls: [10, 11],
      corners: [7, 5],
      yellowCards: [1, 2],
      redCards: [0, 0],
    },
    lineups: {
      home: {
        starting: TEAM_PLAYERS.t7.slice(0, 11),
        subs: TEAM_PLAYERS.t7.slice(11),
        formation: '4-3-3',
      },
      away: {
        starting: TEAM_PLAYERS.t4.slice(0, 11),
        subs: TEAM_PLAYERS.t4.slice(11),
        formation: '4-4-2',
      },
    },
    events: [
      {
        id: 'e38',
        minute: 18,
        type: 'goal',
        team: 'away',
        player: 'Carlos Peña',
        detail: 'Asistencia de Andrés Guardado. Gran habilitación de taco y gol al primer palo.',
      },
      {
        id: 'e39',
        minute: 45,
        type: 'goal',
        team: 'away',
        player: 'Oribe Peralta',
        detail: 'Aprovecha un error defensivo en el despeje para marcar con facilidad.',
      },
      {
        id: 'e40',
        minute: 61,
        type: 'goal',
        team: 'home',
        player: 'David Villa',
        detail: 'Asistencia de Xavi Hernández. Remate exquisito sobre la salida del arquero.',
      },
      {
        id: 'e41',
        minute: 78,
        type: 'goal',
        team: 'away',
        player: 'Giovani dos Santos',
        detail: 'Amaga hacia adentro y define con comba perfecta de zurda.',
      },
    ],
  },

  // --- JORNADA 4 (SCHEDULED) ---
  {
    id: 'm4_1',
    homeTeamId: 't1', // Real Bogotano
    awayTeamId: 't5', // Inter Pradera
    status: 'scheduled',
    date: '2026-07-18',
    time: '14:00',
    pitch: 'Cancha Principal - Club Campestre',
    referee: 'Carlos Alberto Ortega',
    round: 4,
  },
  {
    id: 'm4_2',
    homeTeamId: 't3', // Atlético Campestre
    awayTeamId: 't2', // Deportivo Palermo
    status: 'scheduled',
    date: '2026-07-18',
    time: '16:00',
    pitch: 'Cancha Principal - Club Campestre',
    referee: 'José Manuel Santos',
    round: 4,
  },
  {
    id: 'm4_3',
    homeTeamId: 't4', // F.C. San Isidro
    awayTeamId: 't8', // Estrella del Sur
    status: 'scheduled',
    date: '2026-07-19',
    time: '10:00',
    pitch: 'Cancha Alterna - Sede Pradera',
    referee: 'Diana Carolina Soto',
    round: 4,
  },
  {
    id: 'm4_4',
    homeTeamId: 't7', // La Academia F.C.
    awayTeamId: 't6', // Unión Estudiantil
    status: 'scheduled',
    date: '2026-07-19',
    time: '12:00',
    pitch: 'Cancha Alterna - Sede Pradera',
    referee: 'Andrés Barreto',
    round: 4,
  },
];

// Top Scorers extracted from real stats above
export const TOP_SCORERS: TopScorer[] = [
  { name: 'Daniel Restrepo', teamName: 'Real Bogotano', goals: 4 },
  { name: 'Filippo Inzaghi', teamName: 'Deportivo Palermo', goals: 3 },
  { name: 'Oribe Peralta', teamName: 'F.C. San Isidro', goals: 2 },
  { name: 'David Villa', teamName: 'La Academia F.C.', goals: 2 },
  { name: 'Julián Quiñones', teamName: 'Real Bogotano', goals: 2 },
  { name: 'Arturo Vidal', teamName: 'Atlético Campestre', goals: 1 },
  { name: 'Andrés Iniesta', teamName: 'La Academia F.C.', goals: 1 },
  { name: 'Toni Kroos', teamName: 'Unión Estudiantil', goals: 1 },
];

// Top Assists extracted from real stats above
export const TOP_ASSISTS: TopAssist[] = [
  { name: 'Matías Palacios', teamName: 'Deportivo Palermo', assists: 3 },
  { name: 'Alexis Sánchez', teamName: 'Atlético Campestre', assists: 2 },
  { name: 'Antoine Griezmann', teamName: 'Estrella del Sur', assists: 2 },
  { name: 'Xavi Hernández', teamName: 'La Academia F.C.', assists: 2 },
  { name: 'Toni Kroos', teamName: 'Unión Estudiantil', assists: 2 },
  { name: 'Julián Quiñones', teamName: 'Real Bogotano', assists: 2 },
  { name: 'Andrés Guardado', teamName: 'F.C. San Isidro', assists: 1 },
];

// Overall League Summary Stats
export const LEAGUE_STATS = {
  name: 'Liga de Oro - Torneo Apertura 2026',
  category: 'Fútbol 11 Masculino Libre',
  totalTeams: TEAMS.length,
  matchesPlayed: MATCHES.filter(m => m.status === 'played').length,
  totalMatches: MATCHES.length,
  totalGoals: MATCHES.filter(m => m.status === 'played').reduce((sum, m) => sum + (m.homeScore || 0) + (m.awayScore || 0), 0),
  averageGoals: 0, // calculated dynamically below
  yellowCards: 26,
  redCards: 2,
  nextMatchdayDate: 'Sábado, 18 de Julio de 2026',
};

LEAGUE_STATS.averageGoals = parseFloat((LEAGUE_STATS.totalGoals / LEAGUE_STATS.matchesPlayed).toFixed(2));
